twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['form_themes/tailwind.html.twig']

when@test:
    twig:
        strict_variables: true
      # On déclare ci-dessous le nom de la variable globale
    globals:
        locales: '%app.locales%'
